<?php


return [
    'primary_info' => [
        'institute' => 'Institute',
        'central_id' => 'Central ID',
        'user_id' => 'User ID',
        'district_id' => 'District ID',
        'pngo_id' => 'PNGO ID',
        'status' => 'Status',
        'full_name' => 'Full Name',
        'nick_name' => 'Nick Name',
        'father_name' => 'Father Name',
        'mother_name' => 'Mother Name',
        'sex' => 'Sex',
        'age' => 'Age',
        'disability' => 'Disability',
        'nationality' => 'Nationality',
        'nid_passport' => 'NID/Passport',
        'phone_number' => 'Phone Number',
    ],
    'session_info' => [
        'address' => 'Address',
        'interview_date' => 'Interview Date',
        'interview_time' => 'Interview Time',
        'interview_place' => 'Interview Place',
    ],
    'personal_info' => [
        'marital_status' => 'Marital Status',
        'spouse_name' => 'Spouse Name',
        'education_level' => 'Education Level',
        'occupation' => 'Occupation',
        'monthly_income' => 'Monthly Income',
        'family_informed' => 'Family Informed',
    ],
    'female_prisoner_info' => [
        'children_with_prisoner' => 'Children with Prisoner',
        'child_sex' => 'Child Sex',
        'child_age' => 'Child Age',
    ],
    'guardian_info' => [
        'has_guardian' => 'Has Guardian',
        'guardian_name' => 'Guardian Name',
        'guardian_phone' => 'Guardian Phone',
        'guardian_address' => 'Guardian Address',
        'guardian_relation' => 'Guardian Relation',
        'guardian_surety' => 'Guardian Surety',
    ],
    'lawyer_info' => [
        'has_lawyer' => 'Has Lawyer',
        'lawyer_type' => 'Lawyer Type',
        'lawyer_name' => 'Lawyer Name',
        'lawyer_membership' => 'Lawyer Membership',
        'lawyer_phone' => 'Lawyer Phone',
    ],
    'incident_info' => [
        'incident_details' => 'Incident Details',
    ],
    'court_police_support_info' => [
        'custody_status' => 'Custody Status',
        'charges_details' => 'Charges Details',
        'arrest_date' => 'Arrest Date',
        'case_no' => 'Case No',
    ],
    'assistance_info' => [
        'family_communication_date' => 'Family Communication Date',
        'legal_representation' => 'Legal Representation',
        'legal_representation_date' => 'Legal Representation Date',
        'collected_vokalatnama_date' => 'Collected Vokalatnama Date',
        'collected_case_doc' => 'Collected Case Document',
        'identify_sureties' => 'Identify Sureties',
        'witness_communication_date' => 'Witness Communication Date',
        'medical_report_date' => 'Medical Report Date',
        'legal_assistance_date' => 'Legal Assistance Date',
        'assistance_under_custody_date' => 'Assistance Under Custody Date',
        'referral_service' => 'Referral Service',
        'referral_service_date' => 'Referral Service Date',
    ],
    'result_of_assistance' => [
        'resolved_dispute_date' => 'Resolved Dispute Date',
        'appoint_lawyer_date' => 'Appoint Lawyer Date',
        'release_status' => 'Release Status',
    ],
    'legal_aid_info' => [
        'fine_amount' => 'Fine Amount',
        'release_status_date' => 'Release Status Date',
        'application_mode' => 'Application Mode',
        'application_mode_date' => 'Application Mode Date',
        'received_application' => 'Received Application',
        'reference_no' => 'Reference No',
        'type_of_service' => 'Type of Service',
        'type_of_service_date' => 'Type of Service Date',
    ],
    'service_description' => [
        'service_description' => 'Service Description',
    ],
    'support_in_prison' => [
        'source_of_interview' => 'Source of Interview',
        'prison_reg_no' => 'Prison Reg No',
        'section_no' => 'Section No',
        'present_court' => 'Present Court',
        'lockup_no' => 'Lockup No',
        'entry_date' => 'Entry Date',
        'case_transferred' => 'Case Transferred',
        'current_court' => 'Current Court',
        'case_status' => 'Case Status',
        'co_offenders' => 'Co-Offenders',
        'next_court_date' => 'Next Court Date',
        'facts_of_case' => 'Facts of Case',
    ],
    'imprisonment_info' => [
        'imprisonment_condition' => 'Imprisonment Condition',
        'imprisonment_status' => 'Imprisonment Status',
        'special_condition' => 'Special Condition',
        'surrender_date' => 'Surrender Date',
    ],
    'prison_support_info' => [
        'prison_family_communication' => 'Prison Family Communication',
        'prison_legal_representation' => 'Prison Legal Representation',
        'prison_legal_representation_date' => 'Prison Legal Representation Date',
        'next_court_collection_date' => 'Next Court Collection Date',
        'collected_case_doc_prison' => 'Collected Case Doc (Prison)',
        'identify_sureties_prison_nid' => 'Identify Sureties (Prison NID)',
        'identify_sureties_prison_phone' => 'Identify Sureties (Prison Phone)',
        'witness_communication_prison' => 'Witness Communication (Prison)',
        'bail_bond_submission' => 'Bail Bond Submission',
        'court_order_communication' => 'Court Order Communication',
        'application_certified_copies' => 'Application Certified Copies',
        'appeal_assistance' => 'Appeal Assistance',
        'ministerial_communication' => 'Ministerial Communication',
        'other_legal_assistance' => 'Other Legal Assistance',
        'other_legal_assistance_date' => 'Other Legal Assistance Date',
    ],
    'result_of_prison_assistance' => [
        'released_on' => 'Released On',
        'released_on_date' => 'Released On Date',
        'send_to' => 'Send To',
        'send_to_date' => 'Send To Date',
        'convicted_length' => 'Convicted Length',
        'convicted_sentence_expire' => 'Convicted Sentence Expire',
        'result_of_appeal' => 'Result of Appeal',
        'date_of_reliefe' => 'Date of Relief',
    ],
    'closure_info' => [
        'file_closure_date' => 'File Closure Date',
    ],
];
