<?php

namespace App\Exports;

use App\Models\FormalCase;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class FormalCaseExport implements FromCollection, WithHeadings, WithMapping
{
    public function collection()
    {
        return FormalCase::with(['district:id,name', 'pngo:id,name'])->get();
    }

    public function map($case): array
    {
        return [
            $case->id,
            $case->institute,
            $case->central_id,
            $case->user_id,
            $case->district_id,
            $case->pngo_id,
            $case->status,
            $case->full_name,
            $case->nick_name,
            $case->father_name,
            $case->mother_name,
            $case->sex,
            $case->age,
            $case->disability,
            $case->nationality,
            $case->nid_passport,
            $case->phone_number,
            $case->address,
            $case->interview_date,
            $case->interview_time,
            $case->interview_place,
            $case->marital_status,
            $case->spouse_name,
            $case->education_level,
            $case->occupation,
            $case->monthly_income,
            $case->family_informed,
            $case->children_with_prisoner,
            $case->child_sex,
            $case->child_age,
            $case->has_guardian,
            $case->guardian_name,
            $case->guardian_phone,
            $case->guardian_address,
            $case->guardian_relation,
            $case->guardian_surety,
            $case->has_lawyer,
            $case->lawyer_type,
            $case->lawyer_name,
            $case->lawyer_membership,
            $case->lawyer_phone,
            $case->incident_details,
            $case->custody_status,
            $case->charges_details,
            $case->arrest_date,
            $case->case_no,
            $case->family_communication_date,
            $case->legal_representation,
            $case->legal_representation_date,
            $case->collected_vokalatnama_date,
            $case->collected_case_doc,
            $case->identify_sureties,
            $case->witness_communication_date,
            $case->medical_report_date,
            $case->legal_assistance_date,
            $case->assistance_under_custody_date,
            $case->referral_service,
            $case->referral_service_date,
            $case->resolved_dispute_date,
            $case->appoint_lawyer_date,
            $case->release_status,
            $case->fine_amount,
            $case->release_status_date,
            $case->application_mode,
            $case->application_mode_date,
            $case->received_application,
            $case->reference_no,
            $case->type_of_service,
            $case->type_of_service_date,
            $case->service_description,
            $case->source_of_interview,
            $case->prison_reg_no,
            $case->prison_case_no,
            $case->section_no,
            $case->present_court,
            $case->lockup_no,
            $case->entry_date,
            $case->case_transferred,
            $case->current_court,
            $case->case_status,
            $case->co_offenders,
            $case->next_court_date,
            $case->facts_of_case,
            $case->imprisonment_condition,
            $case->imprisonment_status,
            $case->special_condition,
            $case->prison_arrest_date,
            $case->surrender_date,
            $case->prison_family_communication,
            $case->prison_legal_representation,
            $case->prison_legal_representation_date,
            $case->next_court_collection_date,
            $case->prison_next_court_date,
            $case->collected_case_doc_prison,
            $case->identify_sureties_prison_nid,
            $case->identify_sureties_prison_phone,
            $case->witness_communication_prison,
            $case->bail_bond_submission,
            $case->court_order_communication,
            $case->application_certified_copies,
            $case->appeal_assistance,
            $case->ministerial_communication,
            $case->other_legal_assistance,
            $case->other_legal_assistance_date,
            $case->released_on,
            $case->released_on_date,
            $case->send_to,
            $case->send_to_date,
            $case->convicted_length,
            $case->convicted_sentence_expire,
            $case->result_of_appeal,
            $case->date_of_reliefe,
            $case->result_description,
            $case->file_closure_date,
            $case->created_at,
            $case->updated_at,
        ];
    }


    public function headings(): array
    {
        return [
            'ID',
            'Institute',
            'Central ID',
            'User ID',
            'District ID',
            'PNGO ID',
            'Status',
            'Full Name',
            'Nick Name',
            'Father Name',
            'Mother Name',
            'Sex',
            'Age',
            'Disability',
            'Nationality',
            'NID/Passport',
            'Phone Number',
            'Address',
            'Interview Date',
            'Interview Time',
            'Interview Place',
            'Marital Status',
            'Spouse Name',
            'Education Level',
            'Occupation',
            'Monthly Income',
            'Family Informed',
            'Children With Prisoner',
            'Child Sex',
            'Child Age',
            'Has Guardian',
            'Guardian Name',
            'Guardian Phone',
            'Guardian Address',
            'Guardian Relation',
            'Guardian Surety',
            'Has Lawyer',
            'Lawyer Type',
            'Lawyer Name',
            'Lawyer Membership',
            'Lawyer Phone',
            'Incident Details',
            'Custody Status',
            'Charges Details',
            'Arrest Date',
            'Case No',
            'Family Communication Date',
            'Legal Representation',
            'Legal Representation Date',
            'Collected Vokalatnama Date',
            'Collected Case Doc',
            'Identify Sureties',
            'Witness Communication Date',
            'Medical Report Date',
            'Legal Assistance Date',
            'Assistance Under Custody Date',
            'Referral Service',
            'Referral Service Date',
            'Resolved Dispute Date',
            'Appoint Lawyer Date',
            'Release Status',
            'Fine Amount',
            'Release Status Date',
            'Application Mode',
            'Application Mode Date',
            'Received Application',
            'Reference No',
            'Type of Service',
            'Type of Service Date',
            'Service Description',
            'Source of Interview',
            'Prison Reg No',
            'Prison Case No',
            'Section No',
            'Present Court',
            'Lockup No',
            'Entry Date',
            'Case Transferred',
            'Current Court',
            'Case Status',
            'Co-Offenders',
            'Next Court Date',
            'Facts of Case',
            'Imprisonment Condition',
            'Imprisonment Status',
            'Special Condition',
            'Prison Arrest Date',
            'Surrender Date',
            'Prison Family Communication',
            'Prison Legal Representation',
            'Prison Legal Representation Date',
            'Next Court Collection Date',
            'Prison Next Court Date',
            'Collected Case Doc Prison',
            'Identify Sureties Prison NID',
            'Identify Sureties Prison Phone',
            'Witness Communication Prison',
            'Bail Bond Submission',
            'Court Order Communication',
            'Application Certified Copies',
            'Appeal Assistance',
            'Ministerial Communication',
            'Other Legal Assistance',
            'Other Legal Assistance Date',
            'Released On',
            'Released On Date',
            'Send To',
            'Send To Date',
            'Convicted Length',
            'Convicted Sentence Expire',
            'Result of Appeal',
            'Date of Relief',
            'Result Description',
            'File Closure Date',
            'Created At',
            'Updated At',
        ];
    }

}

